version: "3.7"
services:
  nginx-proxy:
    restart: always
  website:
    image: 357210185381.dkr.ecr.us-east-1.amazonaws.com/wormbase/website:WS275.2
    restart: always
  acedb:
    image: 357210185381.dkr.ecr.us-east-1.amazonaws.com/wormbase/acedb:latest
    expose:
      - "2005"
    volumes:
      - "/usr/local/wormbase/acedb/wormbase:/root/acedb/wormbase"
    restart: always
  upstream-proxy:
    restart: always
